site_name: Macula Greek
repo_url: https://github.com/Clear-Bible/macula-greek
site_url: https://Clear.bible
site_description: Syntax trees, morphology, and linguistic annotations for the Greek Bible 
site_author: Various
# temporary?
docs_dir: doc
nav:
  - Home: index.md
  - Release Notes: ReleaseNotes.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
copyright: CC BY 4.0

theme:
  name: mkdocs
#   name: material
#   feature:
#     tabs: true
#   palette:
#     primary: white
#     accent: blue
# markdown_extensions:
#   - toc:
#       permalink: true
#   - pymdownx.arithmatex:
#       generic: true
